### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by nomuprive** [Goomento/Core#1]
Hi. Which one of Page Builder's module can show Magento 2 shortcode? I have tried the "Text Editor", "Text" and "HTML" but they are not able to output or show a shortcode element on a page built by Goomento.

Thanks!

**Comment by haihv433** [comment]
Hi @williambize 
Im not sure what you meant, there is nothing call "shortcode" within Magento, I make it up for use by Goomento - The Page Builder, can you describe more, 

Btw, this module will not in charge of anything on PageBuilder, it's just a base, where I built Goomento, therefore, can you add the issue to the Page Builder repo with more detail, 

I will close this issue since it not related

**Comment by nomuprive** [comment]
@haihv433 I'm trying to add the shortcode of a Slider module to the Page Builder. It works in Magento 2 page and block, but it doesn't work in Goomento page. Below is a sample of the shortcode in Magento 2.

`{{block class="Nwdthemes\Revslider\Block\Revslider" alias="slider-1"}}`

**Comment by nomuprive** [comment]
@haihv433 Do you have any suggestions about how to integrate the slider in Goomento Page Builder?
